# Generated by Django 5.2.1 on 2025-05-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('cpf', models.CharField(max_length=13)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('age', models.CharField(max_length=3, null=True)),
                ('phone', models.CharField(max_length=25, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
